
FROM node:9.3-slim

# update sources list
RUN apt-get clean
RUN apt-get update

# install basic commands
#   -q  Loggable output - no progress indicator
#   -y  Assume Yes to all queries and do not prompt
RUN apt-get install -qy make
RUN apt-get install -qy git
RUN apt-get install -qy python

RUN npm install -g coffee-script

# clone facilitator-bot w/out 
#   Disable strict host checking for git clone
#   ref: http://debuggable.com/posts/disable-strict-host-checking-for-git-clone:49896ff3-0ac0-4263-9703-1eae4834cda3
RUN echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
RUN git clone https://github.com/shioyang/facilitator-bot.git


RUN npm install



